"""Fetch the dictionary snapshot and write a reproducibility manifest.

Usage:
    python scripts/fetch_dictionary.py [--url URL] [--out data/dictionary]

Downloads the generated dictionary artifact (``basic.json``) from the live
site, verifies nothing, computes SHA-256 / size / row count, and writes:

- ``basic.json``   the raw generated artifact (gitignored)
- ``manifest.json`` provenance record (gitignored alongside the data)

The dictionary data license is UNRESOLVED (see SOURCES.md): the snapshot stays
local, out of git, until licensing is cleared. Nothing here invents a license;
``license_status`` records the audit finding.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_URL = "https://interslavic-dictionary.com/data/basic.json"


def row_count_and_schema(basic_json: dict) -> tuple[int, list]:
    word_list = basic_json.get("wordList", [])
    header = word_list[0] if word_list else []
    rows = len(word_list) - 1 if word_list else 0
    return rows, header


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--url", default=DEFAULT_URL)
    parser.add_argument("--out", default="data/dictionary")
    args = parser.parse_args(argv)

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / "basic.json"

    print(f"fetching {args.url}")
    req = urllib.request.Request(
        args.url,
        headers={"User-Agent": "Mozilla/5.0 (isv-llm-lab reproducibility snapshot)"},
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        raw = resp.read()

    data = json.loads(raw)
    rows, schema = row_count_and_schema(data)

    manifest = {
        "source": "generated dictionary artifact",
        "url": args.url,
        "retrieved_at": datetime.now(timezone.utc).isoformat(),
        "sha256": hashlib.sha256(raw).hexdigest(),
        "size_bytes": len(raw),
        "row_count": rows,
        "schema": schema,
        "license_status": "UNRESOLVED — do not redistribute; keep out of git",
        "notes": (
            "Generated by the sonic16x/medzuslovjansky dictionary app from a "
            "Google Spreadsheet; data provenance (Steen dictionary) license "
            "not stated. See SOURCES.md."
        ),
    }

    target.write_bytes(raw)
    (out_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"wrote   {target} ({len(raw)} bytes, {rows} rows)")
    print(f"sha256  {manifest['sha256']}")
    print(f"wrote   {out_dir / 'manifest.json'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
